name: SpawnMob
author: jordanneil23
main: com.jordanneil23.SpawnMob.Main
version: 3.0
softdepend: [Permissions, PermissionsEX]
commands:
  spawnmob:
    description:
    usage: |
  smob:
    description:
    usage: |
  sm:
    description:
    usage: |
  mspawn:
    description:
    usage: |